package com.bear.todo.generatormodel;

import java.io.Serializable;
import java.util.Date;

public class ToDos implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.id
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.date
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.abstracts
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    private String abstracts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.detail
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.status
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.create_time
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.id
     *
     * @return the value of todos.id
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public ToDos withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.id
     *
     * @param id the value for todos.id
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.date
     *
     * @return the value of todos.date
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public ToDos withDate(Date date) {
        this.setDate(date);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.date
     *
     * @param date the value for todos.date
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.abstracts
     *
     * @return the value of todos.abstracts
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public String getAbstracts() {
        return abstracts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public ToDos withAbstracts(String abstracts) {
        this.setAbstracts(abstracts);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.abstracts
     *
     * @param abstracts the value for todos.abstracts
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public void setAbstracts(String abstracts) {
        this.abstracts = abstracts == null ? null : abstracts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.detail
     *
     * @return the value of todos.detail
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public ToDos withDetail(String detail) {
        this.setDetail(detail);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.detail
     *
     * @param detail the value for todos.detail
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.status
     *
     * @return the value of todos.status
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public ToDos withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.status
     *
     * @param status the value for todos.status
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.create_time
     *
     * @return the value of todos.create_time
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public ToDos withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.create_time
     *
     * @param createTime the value for todos.create_time
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", date=").append(date);
        sb.append(", abstracts=").append(abstracts);
        sb.append(", detail=").append(detail);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}