package com.bear.todo.generatormapper;

import com.bear.todo.generatormodel.ToDos;
import com.bear.todo.generatormodel.ToDosExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface ToDosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    long countByExample(ToDosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    int deleteByExample(ToDosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    @Delete({
        "delete from todos",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    @Insert({
        "insert into todos (id, date, ",
        "abstracts, detail, ",
        "status, create_time)",
        "values (#{id,jdbcType=BIGINT}, #{date,jdbcType=TIMESTAMP}, ",
        "#{abstracts,jdbcType=VARCHAR}, #{detail,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP})"
    })
//    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=true, resultType=Long.class)
    int insert(ToDos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    int insertSelective(ToDos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    List<ToDos> selectByExampleWithRowbounds(ToDosExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    List<ToDos> selectByExample(ToDosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    @Select({
        "select",
        "id, date, abstracts, detail, status, create_time",
        "from todos",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.bear.todo.generatormapper.ToDosMapper.BaseResultMap")
    ToDos selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") ToDos record, @Param("example") ToDosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    int updateByExample(@Param("record") ToDos record, @Param("example") ToDosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    int updateByPrimaryKeySelective(ToDos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Fri May 15 12:53:51 CST 2020
     */
    @Update({
        "update todos",
        "set date = #{date,jdbcType=TIMESTAMP},",
          "abstracts = #{abstracts,jdbcType=VARCHAR},",
          "detail = #{detail,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(ToDos record);
}